/*--- Day 5: Doesn't He Have Intern-Elves For This? ---
Santa needs help figuring out which strings in his text file are naughty or nice.

A nice string is one with all of the following properties:

It contains at least three vowels (aeiou only), like aei, xazegov, or aeiouaeiouaeiou.
It contains at least one letter that appears twice in a row, like xx, abcdde (dd), or aabbccdd (aa, bb, cc, or dd).
It does not contain the strings ab, cd, pq, or xy, even if they are part of one of the other requirements.
For example:

ugknbfddgicrmopn is nice because it has at least three vowels (u...i...o...), a double letter (...dd...), and none of the disallowed substrings.
aaa is nice because it has at least three vowels and a double letter, even though the letters used by different rules overlap.
jchzalrnumimnmhp is naughty because it has no double letter.
haegwjzuvuyypxyu is naughty because it contains the string xy.
dvszwmarrgswjxmb is naughty because it contains only one vowel.
How many strings are nice? */



public class Nice_String_Part_1 {

    public static boolean hasVowels(String string){
        int x = 0;
        for(int i = 0; i < string.length(); i++){
            if(string.charAt(i) == 'a' || string.charAt(i) == 'e' || string.charAt(i) == 'i' || string.charAt(i) == 'o' || string.charAt(i) == 'u'){
                x++;
            }
        }
        if(x >= 3){
            return true;
        }else{
            return false;
        }
    }

    public static boolean hasDoubles(String string){
        int x = 0;
        for(int i = 0; i < string.length() - 1; i++){
            if(string.charAt(i) == string.charAt(i + 1)){
                x = x + 1;
            }
        }
        if(x > 0){
            return true;
        }else{
            return false;
        }
    }

    public static boolean badCouple(String string){
        if(string.contains("ab") || string.contains("cd") || string.contains("pq") || string.contains("xy")){
            return true;
        }else{
            return false;
        }
    }
    public static void main(String []args){
        int x = 0;
        String string = "zgsnvdmlfuplrubt\r\n" + //
                        "vlhagaovgqjmgvwq\r\n" + //
                        "ffumlmqwfcsyqpss\r\n" + //
                        "zztdcqzqddaazdjp\r\n" + //
                        "eavfzjajkjesnlsb\r\n" + //
                        "urrvucyrzzzooxhx\r\n" + //
                        "xdwduffwgcptfwad\r\n" + //
                        "orbryxwrmvkrsxsr\r\n" + //
                        "jzfeybjlgqikjcow\r\n" + //
                        "mayoqiswqqryvqdi\r\n" + //
                        "iiyrkoujhgpgkcvx\r\n" + //
                        "egcgupjkqwfiwsjl\r\n" + //
                        "zbgtglaqqolttgng\r\n" + //
                        "eytquncjituzzhsx\r\n" + //
                        "dtfkgggvqadhqbwb\r\n" + //
                        "zettygjpcoedwyio\r\n" + //
                        "rwgwbwzebsnjmtln\r\n" + //
                        "esbplxhvzzgawctn\r\n" + //
                        "vnvshqgmbotvoine\r\n" + //
                        "wflxwmvbhflkqxvo\r\n" + //
                        "twdjikcgtpvlctte\r\n" + //
                        "minfkyocskvgubvm\r\n" + //
                        "sfxhhdhaopajbzof\r\n" + //
                        "sofkjdtalvhgwpql\r\n" + //
                        "uqfpeauqzumccnrc\r\n" + //
                        "tdflsbtiiepijanf\r\n" + //
                        "dhfespzrhecigzqb\r\n" + //
                        "xobfthcuuzhvhzpn\r\n" + //
                        "olgjglxaotocvrhw\r\n" + //
                        "jhkzpfcskutwlwge\r\n" + //
                        "zurkakkkpchzxjhq\r\n" + //
                        "hekxiofhalvmmkdl\r\n" + //
                        "azvxuwwfmjdpjskj\r\n" + //
                        "arsvmfznblsqngvb\r\n" + //
                        "ldhkzhejofreaucc\r\n" + //
                        "adrphwlkehqkrdmo\r\n" + //
                        "wmveqrezfkaivvaw\r\n" + //
                        "iyphmphgntinfezg\r\n" + //
                        "blomkvgslfnvspem\r\n" + //
                        "cgpaqjvzhbumckwo\r\n" + //
                        "ydhqjcuotkeyurpx\r\n" + //
                        "sbtzboxypnmdaefr\r\n" + //
                        "vxrkhvglynljgqrg\r\n" + //
                        "ttgrkjjrxnxherxd\r\n" + //
                        "hinyfrjdiwytetkw\r\n" + //
                        "sufltffwqbugmozk\r\n" + //
                        "tohmqlzxxqzinwxr\r\n" + //
                        "jbqkhxfokaljgrlg\r\n" + //
                        "fvjeprbxyjemyvuq\r\n" + //
                        "gmlondgqmlselwah\r\n" + //
                        "ubpwixgxdloqnvjp\r\n" + //
                        "lxjfhihcsajxtomj\r\n" + //
                        "qouairhvrgpjorgh\r\n" + //
                        "nloszcwcxgullvxb\r\n" + //
                        "myhsndsttanohnjn\r\n" + //
                        "zjvivcgtjwenyilz\r\n" + //
                        "qaqlyoyouotsmamm\r\n" + //
                        "tadsdceadifqthag\r\n" + //
                        "mafgrbmdhpnlbnks\r\n" + //
                        "aohjxahenxaermrq\r\n" + //
                        "ovvqestjhbuhrwlr\r\n" + //
                        "lnakerdnvequfnqb\r\n" + //
                        "agwpwsgjrtcjjikz\r\n" + //
                        "lhlysrshsmzryzes\r\n" + //
                        "xopwzoaqtlukwwdu\r\n" + //
                        "xsmfrfteyddrqufn\r\n" + //
                        "ohnxbykuvvlbbxpf\r\n" + //
                        "bbdlivmchvzfuhoc\r\n" + //
                        "vtacidimfcfyobhf\r\n" + //
                        "tinyzzddgcnmiabd\r\n" + //
                        "tcjzxftqcqrivqhn\r\n" + //
                        "vgnduqyfpokbmzim\r\n" + //
                        "revkvaxnsxospyow\r\n" + //
                        "ydpgwxxoxlywxcgi\r\n" + //
                        "wzuxupbzlpzmikel\r\n" + //
                        "nscghlafavnsycjh\r\n" + //
                        "xorwbquzmgmcapon\r\n" + //
                        "asmtiycegeobfxrn\r\n" + //
                        "eqjzvgkxgtlyuxok\r\n" + //
                        "mmjrskloposgjoqu\r\n" + //
                        "gceqosugbkvytfto\r\n" + //
                        "khivvoxkvhrgwzjl\r\n" + //
                        "qtmejuxbafroifjt\r\n" + //
                        "ttmukbmpoagthtfl\r\n" + //
                        "bxqkvuzdbehtduwv\r\n" + //
                        "gvblrpzjylanoggj\r\n" + //
                        "cltewhyjxdbmbtqj\r\n" + //
                        "fbkgedqvomdipklj\r\n" + //
                        "uxvuplhenqawfcjt\r\n" + //
                        "fkdjmayiawdkycva\r\n" + //
                        "gnloqfgbnibzyidh\r\n" + //
                        "kyzorvtopjiyyyqg\r\n" + //
                        "drckpekhpgrioblt\r\n" + //
                        "tvhrkmbnpmkkrtki\r\n" + //
                        "khaldwntissbijiz\r\n" + //
                        "aoojqakosnaxosom\r\n" + //
                        "xfptccznbgnpfyqw\r\n" + //
                        "moqdwobwhjxhtrow\r\n" + //
                        "chfwivedutskovri\r\n" + //
                        "gprkyalfnpljcrmi\r\n" + //
                        "pwyshpwjndasykst\r\n" + //
                        "xuejivogihttzimd\r\n" + //
                        "bugepxgpgahtsttl\r\n" + //
                        "zufmkmuujavcskpq\r\n" + //
                        "urybkdyvsrosrfro\r\n" + //
                        "isjxqmlxwtqmulbg\r\n" + //
                        "pxctldxgqjqhulgz\r\n" + //
                        "hclsekryiwhqqhir\r\n" + //
                        "hbuihpalwuidjpcq\r\n" + //
                        "ejyqcxmfczqfhbxa\r\n" + //
                        "xljdvbucuxnnaysv\r\n" + //
                        "irqceqtqwemostbb\r\n" + //
                        "anfziqtpqzqdttnz\r\n" + //
                        "cgfklbljeneeqfub\r\n" + //
                        "zudyqkuqqtdcpmuo\r\n" + //
                        "iuvhylvznmhbkbgg\r\n" + //
                        "mpgppmgfdzihulnd\r\n" + //
                        "argwmgcvqqkxkrdi\r\n" + //
                        "pdhrfvdldkfihlou\r\n" + //
                        "cbvqnjrvrsnqzfob\r\n" + //
                        "lkvovtsqanohzcmm\r\n" + //
                        "vxoxjdyoylqcnyzt\r\n" + //
                        "kurdpaqiaagiwjle\r\n" + //
                        "gwklwnazaxfkuekn\r\n" + //
                        "rbaamufphjsjhbdl\r\n" + //
                        "tzbrvaqvizhsisbd\r\n" + //
                        "pbcqlbfjvlideiub\r\n" + //
                        "hiwoetbfywaeddtx\r\n" + //
                        "fjirczxtuupfywyf\r\n" + //
                        "omeoegeyyospreem\r\n" + //
                        "ozbbpupqpsskvrjh\r\n" + //
                        "pzvcxkvjdiyeyhxa\r\n" + //
                        "odclumkenabcsfzr\r\n" + //
                        "npdyqezqdjqaszvm\r\n" + //
                        "yodkwzmrhtexfrqa\r\n" + //
                        "rjcmmggjtactfrxz\r\n" + //
                        "mioxfingsfoimual\r\n" + //
                        "aqskaxjjborspfaa\r\n" + //
                        "wientdsttkevjtkf\r\n" + //
                        "tdaswkzckmxnfnct\r\n" + //
                        "voucjhzvkkhuwoqk\r\n" + //
                        "boaaruhalgaamqmh\r\n" + //
                        "iufzxutxymorltvb\r\n" + //
                        "pfbyvbayvnrpijpo\r\n" + //
                        "obztirulgyfthgcg\r\n" + //
                        "ntrenvhwxypgtjwy\r\n" + //
                        "ephlkipjfnjfjrns\r\n" + //
                        "pkjhurzbmobhszpx\r\n" + //
                        "gqbnjvienzqfbzvj\r\n" + //
                        "wjelolsrbginwnno\r\n" + //
                        "votanpqpccxqricj\r\n" + //
                        "bxyuyiglnmbtvehi\r\n" + //
                        "qyophcjfknbcbjrb\r\n" + //
                        "anoqkkbcdropskhj\r\n" + //
                        "tcnyqaczcfffkrtl\r\n" + //
                        "rsvqimuqbuddozrf\r\n" + //
                        "meppxdrenexxksdt\r\n" + //
                        "tyfhfiynzwadcord\r\n" + //
                        "wayrnykevdmywycf\r\n" + //
                        "mhowloqnppswyzbu\r\n" + //
                        "tserychksuwrgkxz\r\n" + //
                        "xycjvvsuaxsbrqal\r\n" + //
                        "fkrdsgaoqdcqwlpn\r\n" + //
                        "vrabcmlhuktigecp\r\n" + //
                        "xgxtdsvpaymzhurx\r\n" + //
                        "ciabcqymnchhsxkc\r\n" + //
                        "eqxadalcxzocsgtr\r\n" + //
                        "tsligrgsjtrnzrex\r\n" + //
                        "qeqgmwipbspkbbfq\r\n" + //
                        "vzkzsjujltnqwliw\r\n" + //
                        "ldrohvodgbxokjxz\r\n" + //
                        "jkoricsxhipcibrq\r\n" + //
                        "qzquxawqmupeujrr\r\n" + //
                        "mizpuwqyzkdbahvk\r\n" + //
                        "suupfxbtoojqvdca\r\n" + //
                        "ywfmuogvicpywpwm\r\n" + //
                        "uevmznxmsxozhobl\r\n" + //
                        "vjbyhsemwfwdxfxk\r\n" + //
                        "iyouatgejvecmtin\r\n" + //
                        "tcchwpuouypllcxe\r\n" + //
                        "lgnacnphdiobdsef\r\n" + //
                        "uoxjfzmdrmpojgbf\r\n" + //
                        "lqbxsxbqqhpjhfxj\r\n" + //
                        "knpwpcnnimyjlsyz\r\n" + //
                        "fezotpoicsrshfnh\r\n" + //
                        "dkiwkgpmhudghyhk\r\n" + //
                        "yzptxekgldksridv\r\n" + //
                        "pckmzqzyiyzdbcts\r\n" + //
                        "oqshafncvftvwvsi\r\n" + //
                        "yynihvdywxupqmbt\r\n" + //
                        "iwmbeunfiuhjaaic\r\n" + //
                        "pkpkrqjvgocvaxjs\r\n" + //
                        "ieqspassuvquvlyz\r\n" + //
                        "xshhahjaxjoqsjtl\r\n" + //
                        "fxrrnaxlqezdcdvd\r\n" + //
                        "pksrohfwlaqzpkdd\r\n" + //
                        "ravytrdnbxvnnoyy\r\n" + //
                        "atkwaifeobgztbgo\r\n" + //
                        "inkcabgfdobyeeom\r\n" + //
                        "ywpfwectajohqizp\r\n" + //
                        "amcgorhxjcybbisv\r\n" + //
                        "mbbwmnznhafsofvr\r\n" + //
                        "wofcubucymnhuhrv\r\n" + //
                        "mrsamnwvftzqcgta\r\n" + //
                        "tlfyqoxmsiyzyvgv\r\n" + //
                        "ydceguvgotylwtea\r\n" + //
                        "btyvcjqhsygunvle\r\n" + //
                        "usquiquspcdppqeq\r\n" + //
                        "kifnymikhhehgote\r\n" + //
                        "ybvkayvtdpgxfpyn\r\n" + //
                        "oulxagvbavzmewnx\r\n" + //
                        "tvvpekhnbhjskzpj\r\n" + //
                        "azzxtstaevxurboa\r\n" + //
                        "nfmwtfgrggmqyhdf\r\n" + //
                        "ynyzypdmysfwyxgr\r\n" + //
                        "iaobtgubrcyqrgmk\r\n" + //
                        "uyxcauvpyzabbzgv\r\n" + //
                        "fbasfnwiguasoedc\r\n" + //
                        "mgmjoalkbvtljilq\r\n" + //
                        "szgkxiqkufdvtksb\r\n" + //
                        "xgfzborpavdmhiuj\r\n" + //
                        "hmuiwnsonvfgcrva\r\n" + //
                        "zolcffdtobfntifb\r\n" + //
                        "mvzgcsortkugvqjr\r\n" + //
                        "pbbpgraaldqvzwhs\r\n" + //
                        "zvsxegchksgnhpuv\r\n" + //
                        "kdpdboaxsuxfswhx\r\n" + //
                        "jdfggigejfupabth\r\n" + //
                        "tpeddioybqemyvqz\r\n" + //
                        "mxsntwuesonybjby\r\n" + //
                        "tzltdsiojfvocige\r\n" + //
                        "ubtdrneozoejiqrv\r\n" + //
                        "fusyucnhncoxqzql\r\n" + //
                        "nlifgomoftdvkpby\r\n" + //
                        "pyikzbxoapffbqjw\r\n" + //
                        "hzballplvzcsgjug\r\n" + //
                        "ymjyigsfehmdsvgz\r\n" + //
                        "vpqgyxknniunksko\r\n" + //
                        "ffkmaqsjxgzclsnq\r\n" + //
                        "jcuxthbedplxhslk\r\n" + //
                        "ymlevgofmharicfs\r\n" + //
                        "nyhbejkndhqcoisy\r\n" + //
                        "rjntxasfjhnlizgm\r\n" + //
                        "oqlnuxtzhyiwzeto\r\n" + //
                        "tntthdowhewszitu\r\n" + //
                        "rmxyoceuwhsvfcua\r\n" + //
                        "qpgsjzwenzbxyfgw\r\n" + //
                        "sumguxpdkocyagpu\r\n" + //
                        "ymfrbxwrawejkduu\r\n" + //
                        "hetgrtmojolbmsuf\r\n" + //
                        "qzqizpiyfasgttex\r\n" + //
                        "qnmoemcpuckzsshx\r\n" + //
                        "ddyqiihagcmnxccu\r\n" + //
                        "oirwxyfxxyktgheo\r\n" + //
                        "phpaoozbdogbushy\r\n" + //
                        "uctjdavsimsrnvjn\r\n" + //
                        "aurbbphvjtzipnuh\r\n" + //
                        "hpbtrubopljmltep\r\n" + //
                        "pyyvkthqfsxqhrxg\r\n" + //
                        "jdxaiqzkepxbfejk\r\n" + //
                        "ukgnwbnysrzvqzlw\r\n" + //
                        "lfkatkvcssnlpthd\r\n" + //
                        "ucsyecgshklhqmsc\r\n" + //
                        "rwdcbdchuahkvmga\r\n" + //
                        "rxkgqakawgpwokum\r\n" + //
                        "hbuyxeylddfgorgu\r\n" + //
                        "tbllspqozaqzglkz\r\n" + //
                        "rqfwizjlbwngdvvi\r\n" + //
                        "xuxduyzscovachew\r\n" + //
                        "kouiuxckkvmetvdy\r\n" + //
                        "ycyejrpwxyrweppd\r\n" + //
                        "trctlytzwiisjamx\r\n" + //
                        "vtvpjceydunjdbez\r\n" + //
                        "gmtlejdsrbfofgqy\r\n" + //
                        "jgfbgtkzavcjlffj\r\n" + //
                        "tyudxlpgraxzchdk\r\n" + //
                        "gyecxacqitgozzgd\r\n" + //
                        "rxaocylfabmmjcvt\r\n" + //
                        "tornfzkzhjyofzqa\r\n" + //
                        "kocjcrqcsvagmfqv\r\n" + //
                        "zfrswnskuupivzxb\r\n" + //
                        "cunkuvhbepztpdug\r\n" + //
                        "pmpfnmklqhcmrtmf\r\n" + //
                        "tfebzovjwxzumxap\r\n" + //
                        "xpsxgaswavnzkzye\r\n" + //
                        "lmwijdothmxclqbr\r\n" + //
                        "upqxhmctbltxkarl\r\n" + //
                        "axspehytmyicthmq\r\n" + //
                        "xdwrhwtuooikehbk\r\n" + //
                        "tpggalqsytvmwerj\r\n" + //
                        "jodysbwnymloeqjf\r\n" + //
                        "rxbazvwuvudqlydn\r\n" + //
                        "ibizqysweiezhlqa\r\n" + //
                        "uexgmotsqjfauhzp\r\n" + //
                        "ldymyvumyhyamopg\r\n" + //
                        "vbxvlvthgzgnkxnf\r\n" + //
                        "pyvbrwlnatxigbrp\r\n" + //
                        "azxynqididtrwokb\r\n" + //
                        "lwafybyhpfvoawto\r\n" + //
                        "ogqoivurfcgspytw\r\n" + //
                        "cinrzzradwymqcgu\r\n" + //
                        "sgruxdvrewgpmypu\r\n" + //
                        "snfnsbywuczrshtd\r\n" + //
                        "xfzbyqtyxuxdutpw\r\n" + //
                        "fmpvjwbulmncykbo\r\n" + //
                        "ljnwoslktrrnffwo\r\n" + //
                        "ceaouqquvvienszn\r\n" + //
                        "yjomrunrxjyljyge\r\n" + //
                        "xpmjsapbnsdnbkdi\r\n" + //
                        "uetoytptktkmewre\r\n" + //
                        "eixsvzegkadkfbua\r\n" + //
                        "afaefrwhcosurprw\r\n" + //
                        "bwzmmvkuaxiymzwc\r\n" + //
                        "gejyqhhzqgsrybni\r\n" + //
                        "gjriqsfrhyguoiiw\r\n" + //
                        "gtfyomppzsruhuac\r\n" + //
                        "ogemfvmsdqqkfymr\r\n" + //
                        "jgzbipsygirsnydh\r\n" + //
                        "zghvlhpjnvqmocgr\r\n" + //
                        "ngvssuwrbtoxtrka\r\n" + //
                        "ietahyupkbuisekn\r\n" + //
                        "gqxqwjizescbufvl\r\n" + //
                        "eiprekzrygkncxzl\r\n" + //
                        "igxfnxtwpyaamkxf\r\n" + //
                        "soqjdkxcupevbren\r\n" + //
                        "fspypobyzdwstxak\r\n" + //
                        "qstcgawvqwtyyidf\r\n" + //
                        "gsccjacboqvezxvd\r\n" + //
                        "bfsblokjvrqzphmc\r\n" + //
                        "srezeptvjmncqkec\r\n" + //
                        "opmopgyabjjjoygt\r\n" + //
                        "msvbufqexfrtecbf\r\n" + //
                        "uiaqweyjiulplelu\r\n" + //
                        "pbkwhjsibtwjvswi\r\n" + //
                        "xwwzstmozqarurrq\r\n" + //
                        "nytptwddwivtbgyq\r\n" + //
                        "ejxvsufbzwhzpabr\r\n" + //
                        "jouozvzuwlfqzdgh\r\n" + //
                        "gfgugjihbklbenrk\r\n" + //
                        "lwmnnhiuxqsfvthv\r\n" + //
                        "bzvwbknfmaeahzhi\r\n" + //
                        "cgyqswikclozyvnu\r\n" + //
                        "udmkpvrljsjiagzi\r\n" + //
                        "zzuhqokgmisguyna\r\n" + //
                        "ekwcdnjzuctsdoua\r\n" + //
                        "eueqkdrnzqcaecyd\r\n" + //
                        "lnibwxmokbxhlris\r\n" + //
                        "fdrbftgjljpzwhea\r\n" + //
                        "iabvuhhjsxmqfwld\r\n" + //
                        "qgogzkynrgejakta\r\n" + //
                        "mfcqftytemgnpupp\r\n" + //
                        "klvhlhuqhosvjuqk\r\n" + //
                        "gdokmxcgoqvzvaup\r\n" + //
                        "juududyojcazzgvr\r\n" + //
                        "fyszciheodgmnotg\r\n" + //
                        "yfpngnofceqfvtfs\r\n" + //
                        "cahndkfehjumwavc\r\n" + //
                        "dxsvscqukljxcqyi\r\n" + //
                        "cqukcjtucxwrusji\r\n" + //
                        "vevmmqlehvgebmid\r\n" + //
                        "ahswsogfrumzdofy\r\n" + //
                        "ftasbklvdquaxhxb\r\n" + //
                        "tsdeumygukferuif\r\n" + //
                        "ybfgbwxaaitpwryg\r\n" + //
                        "djyaoycbymezglio\r\n" + //
                        "trzrgxdjqnmlnzpn\r\n" + //
                        "rumwchfihhihpqui\r\n" + //
                        "ffrvnsgrnzemksif\r\n" + //
                        "oizlksxineqknwzd\r\n" + //
                        "cirqcprftpjzrxhk\r\n" + //
                        "zrhemeqegmzrpufd\r\n" + //
                        "kqgatudhxgzlgkey\r\n" + //
                        "syjugymeajlzffhq\r\n" + //
                        "nlildhmgnwlopohp\r\n" + //
                        "flcszztfbesqhnyz\r\n" + //
                        "ohzicmqsajyqptrw\r\n" + //
                        "ebyszucgozsjbelq\r\n" + //
                        "enxbgvvcuqeloxud\r\n" + //
                        "ubwnvecbsmhkxwuk\r\n" + //
                        "noifliyxvlkqphbo\r\n" + //
                        "hazlqpetgugxxsiz\r\n" + //
                        "ihdzoerqwqhgajzb\r\n" + //
                        "ivrdwdquxzhdrzar\r\n" + //
                        "synwycdvrupablib\r\n" + //
                        "mqkdjkntblnmtvxj\r\n" + //
                        "qmmvoylxymyovrnq\r\n" + //
                        "pjtuxskkowutltlq\r\n" + //
                        "gchrqtloggkrjciz\r\n" + //
                        "namzqovvsdipazae\r\n" + //
                        "yfokqhkmakyjzmys\r\n" + //
                        "iapxlbuoiwqfnozm\r\n" + //
                        "fbcmlcekgfdurqxe\r\n" + //
                        "ednzgtczbplwxjlq\r\n" + //
                        "gdvsltzpywffelsp\r\n" + //
                        "oaitrrmpqdvduqej\r\n" + //
                        "gseupzwowmuuibjo\r\n" + //
                        "dfzsffsqpaqoixhh\r\n" + //
                        "tclhzqpcvbshxmgx\r\n" + //
                        "cfqkptjrulxiabgo\r\n" + //
                        "iraiysmwcpmtklhf\r\n" + //
                        "znwjlzodhktjqwlm\r\n" + //
                        "lcietjndlbgxzjht\r\n" + //
                        "gdkcluwjhtaaprfo\r\n" + //
                        "vbksxrfznjzwvmmt\r\n" + //
                        "vpfftxjfkeltcojl\r\n" + //
                        "thrmzmeplpdespnh\r\n" + //
                        "yafopikiqswafsit\r\n" + //
                        "xxbqgeblfruklnhs\r\n" + //
                        "qiufjijzbcpfdgig\r\n" + //
                        "ikksmllfyvhyydmi\r\n" + //
                        "sknufchjdvccccta\r\n" + //
                        "wpdcrramajdoisxr\r\n" + //
                        "grnqkjfxofpwjmji\r\n" + //
                        "lkffhxonjskyccoh\r\n" + //
                        "npnzshnoaqayhpmb\r\n" + //
                        "fqpvaamqbrnatjia\r\n" + //
                        "oljkoldhfggkfnfc\r\n" + //
                        "ihpralzpqfrijynm\r\n" + //
                        "gvaxadkuyzgbjpod\r\n" + //
                        "onchdguuhrhhspen\r\n" + //
                        "uefjmufwlioenaus\r\n" + //
                        "thifdypigyihgnzo\r\n" + //
                        "ugqblsonqaxycvkg\r\n" + //
                        "yevmbiyrqdqrmlbw\r\n" + //
                        "bvpvwrhoyneorcmm\r\n" + //
                        "gbyjqzcsheaxnyib\r\n" + //
                        "knhsmdjssycvuoqf\r\n" + //
                        "nizjxiwdakpfttyh\r\n" + //
                        "nwrkbhorhfqqoliz\r\n" + //
                        "ynsqwvwuwzqpzzwp\r\n" + //
                        "yitscrgexjfclwwh\r\n" + //
                        "dhajwxqdbtrfltzz\r\n" + //
                        "bmrfylxhthiaozpv\r\n" + //
                        "frvatcvgknjhcndw\r\n" + //
                        "xlvtdmpvkpcnmhya\r\n" + //
                        "pxpemuzuqzjlmtoc\r\n" + //
                        "dijdacfteteypkoq\r\n" + //
                        "knrcdkrvywagglnf\r\n" + //
                        "fviuajtspnvnptia\r\n" + //
                        "xvlqzukmwbcjgwho\r\n" + //
                        "bazlsjdsjoeuvgoz\r\n" + //
                        "nslzmlhosrjarndj\r\n" + //
                        "menvuwiuymknunwm\r\n" + //
                        "uavfnvyrjeiwqmuu\r\n" + //
                        "yrfowuvasupngckz\r\n" + //
                        "taevqhlrcohlnwye\r\n" + //
                        "skcudnogbncusorn\r\n" + //
                        "omtnmkqnqedsajfv\r\n" + //
                        "yqmgsqdgsuysqcts\r\n" + //
                        "odsnbtyimikkbmdd\r\n" + //
                        "vuryaohxdvjllieb\r\n" + //
                        "dhaxldeywwsfamlo\r\n" + //
                        "opobvtchezqnxpak\r\n" + //
                        "pzfnegouvsrfgvro\r\n" + //
                        "rzkcgpxdslzrdktu\r\n" + //
                        "ksztdtqzxvhuryam\r\n" + //
                        "ctnqnhkcooqipgkh\r\n" + //
                        "pyqbbvrzdittqbgm\r\n" + //
                        "koennvmolejeftij\r\n" + //
                        "rvzlreqikqlgyczj\r\n" + //
                        "xrnujfoyhonzkdgd\r\n" + //
                        "mmsmhkxaiqupfjil\r\n" + //
                        "ypjwoemqizddvyfd\r\n" + //
                        "qgugcxnbhvgahykj\r\n" + //
                        "cviodlsrtimbkgmy\r\n" + //
                        "xbfbbechhmrjxhnw\r\n" + //
                        "psuipaoucfczfxkp\r\n" + //
                        "hdhwcpeuptgqqvim\r\n" + //
                        "gsxlruhjeaareilr\r\n" + //
                        "vgyqonnljuznyrhk\r\n" + //
                        "eewezahlumervpyu\r\n" + //
                        "iiolebrxfadtnigy\r\n" + //
                        "tdadlrodykrdfscn\r\n" + //
                        "ocvdtzjxrhtjurpo\r\n" + //
                        "gidljbuvuovkhhrf\r\n" + //
                        "qwfcpilbjwzboohd\r\n" + //
                        "xzohxonlezuiupbg\r\n" + //
                        "vslpbkkqgvgbcbix\r\n" + //
                        "pivzqrzfxosbstzn\r\n" + //
                        "fyqcfboevcqmbhhs\r\n" + //
                        "yqsrneacnlxswojx\r\n" + //
                        "heicqpxxyrwcbsjz\r\n" + //
                        "yzynmnnoumkmlbeh\r\n" + //
                        "bncadbjdvvmczylw\r\n" + //
                        "hlnjskgfzbgmigfn\r\n" + //
                        "fphpszymugpcykka\r\n" + //
                        "zbifcktanxpmufvy\r\n" + //
                        "saklpkhoyfeqbguy\r\n" + //
                        "nqtqfcfxmpivnjyo\r\n" + //
                        "locygrwerxlsvzqm\r\n" + //
                        "qqflecydqvlogjme\r\n" + //
                        "njklmixvgkzpgppf\r\n" + //
                        "ugzkpjwjflaswyma\r\n" + //
                        "lriousvkbeftslcy\r\n" + //
                        "nsvsauxzfbbotgmh\r\n" + //
                        "tblcpuhjyybrlica\r\n" + //
                        "hqwshxcilwtmxrsf\r\n" + //
                        "xojwroydfeoqupup\r\n" + //
                        "tikuzsrogpnohpib\r\n" + //
                        "layenyqgxdfggloc\r\n" + //
                        "nqsvjvbrpuxkqvmq\r\n" + //
                        "ivchgxkdlfjdzxmk\r\n" + //
                        "uoghiuosiiwiwdws\r\n" + //
                        "twsgsfzyszsfinlc\r\n" + //
                        "waixcmadmhtqvcmd\r\n" + //
                        "zkgitozgrqehtjkw\r\n" + //
                        "xbkmyxkzqyktmpfi\r\n" + //
                        "qlyapfmlybmatwxn\r\n" + //
                        "ntawlvcpuaebuypf\r\n" + //
                        "clhebxqdkcyndyof\r\n" + //
                        "nrcxuceywiklpemc\r\n" + //
                        "lmurgiminxpapzmq\r\n" + //
                        "obalwqlkykzflxou\r\n" + //
                        "huvcudpiryefbcye\r\n" + //
                        "zlxbddpnyuyapach\r\n" + //
                        "gqfwzfislmwzyegy\r\n" + //
                        "jhynkjtxedmemlob\r\n" + //
                        "hmrnvjodnsfiukex\r\n" + //
                        "pstmikjykzyavfef\r\n" + //
                        "wuwpnscrwzsyalyt\r\n" + //
                        "hksvadripgdgwynm\r\n" + //
                        "tvpfthzjleqfxwkh\r\n" + //
                        "xpmrxxepkrosnrco\r\n" + //
                        "qjkqecsnevlhqsly\r\n" + //
                        "jjnrfsxzzwkhnwdm\r\n" + //
                        "pehmzrzsjngccale\r\n" + //
                        "bsnansnfxduritrr\r\n" + //
                        "ejzxkefwmzmbxhlb\r\n" + //
                        "pceatehnizeujfrs\r\n" + //
                        "jtidrtgxopyeslzl\r\n" + //
                        "sytaoidnamfwtqcr\r\n" + //
                        "iabjnikomkgmyirr\r\n" + //
                        "eitavndozoezojsi\r\n" + //
                        "wtsbhaftgrbqfsmm\r\n" + //
                        "vvusvrivsmhtfild\r\n" + //
                        "qifbtzszfyzsjzyx\r\n" + //
                        "ifhhjpaqatpbxzau\r\n" + //
                        "etjqdimpyjxiuhty\r\n" + //
                        "fvllmbdbsjozxrip\r\n" + //
                        "tjtgkadqkdtdlkpi\r\n" + //
                        "xnydmjleowezrecn\r\n" + //
                        "vhcbhxqalroaryfn\r\n" + //
                        "scgvfqsangfbhtay\r\n" + //
                        "lbufpduxwvdkwhmb\r\n" + //
                        "tshipehzspkhmdoi\r\n" + //
                        "gtszsebsulyajcfl\r\n" + //
                        "dlrzswhxajcivlgg\r\n" + //
                        "kgjruggcikrfrkrw\r\n" + //
                        "xxupctxtmryersbn\r\n" + //
                        "hljjqfjrubzozxts\r\n" + //
                        "giaxjhcwazrenjzs\r\n" + //
                        "tyffxtpufpxylpye\r\n" + //
                        "jfugdxxyfwkzqmgv\r\n" + //
                        "kbgufbosjghahacw\r\n" + //
                        "xpbhhssgegmthwxb\r\n" + //
                        "npefofiharjypyzk\r\n" + //
                        "velxsseyxuhrpycy\r\n" + //
                        "sglslryxsiwwqzfw\r\n" + //
                        "susohnlpelojhklv\r\n" + //
                        "lfnpqfvptqhogdmk\r\n" + //
                        "vtcrzetlekguqyle\r\n" + //
                        "jlyggqdtamcjiuxn\r\n" + //
                        "olxxqfgizjmvigvl\r\n" + //
                        "cyypypveppxxxfuq\r\n" + //
                        "hewmxtlzfqoqznwd\r\n" + //
                        "jzgxxybfeqfyzsmp\r\n" + //
                        "xzvvndrhuejnzesx\r\n" + //
                        "esiripjpvtqqwjkv\r\n" + //
                        "xnhrwhjtactofwrd\r\n" + //
                        "knuzpuogbzplofqx\r\n" + //
                        "tihycsdwqggxntqk\r\n" + //
                        "xkfywvvugkdalehs\r\n" + //
                        "cztwdivxagtqjjel\r\n" + //
                        "dsaslcagopsbfioy\r\n" + //
                        "gmowqtkgrlqjimbl\r\n" + //
                        "ctcomvdbiatdvbsd\r\n" + //
                        "gujyrnpsssxmqjhz\r\n" + //
                        "nygeovliqjfauhjf\r\n" + //
                        "mmgmcvnuppkbnonz\r\n" + //
                        "bhipnkoxhzcotwel\r\n" + //
                        "wkwpgedgxvpltqid\r\n" + //
                        "mliajvpdocyzcbot\r\n" + //
                        "kqjhsipuibyjuref\r\n" + //
                        "zqdczykothbgxwsy\r\n" + //
                        "koirtljkuqzxioaz\r\n" + //
                        "audpjvhmqzvhzqas\r\n" + //
                        "cxyhxlhntyidldfx\r\n" + //
                        "iasgocejboxjgtkx\r\n" + //
                        "abehujmqotwcufxp\r\n" + //
                        "fmlrzqmazajxeedl\r\n" + //
                        "knswpkekbacuxfby\r\n" + //
                        "yvyalnvrxgstqhxm\r\n" + //
                        "sjnrljfrfuyqfwuw\r\n" + //
                        "ssaqruwarlvxrqzm\r\n" + //
                        "iaxbpeqqzlcwfqjz\r\n" + //
                        "uwyxshjutkanvvsc\r\n" + //
                        "uxwrlwbblcianvnb\r\n" + //
                        "nodtifgrxdojhneh\r\n" + //
                        "mloxjfusriktxrms\r\n" + //
                        "lkfzrwulbctupggc\r\n" + //
                        "gcrjljatfhitcgfj\r\n" + //
                        "tkdfxeanwskaivqs\r\n" + //
                        "ypyjxqtmitwubbgt\r\n" + //
                        "ssxbygzbjsltedjj\r\n" + //
                        "zdrsnoorwqfalnha\r\n" + //
                        "xlgmissaiqmowppd\r\n" + //
                        "azhbwhiopwpguiuo\r\n" + //
                        "fydlahgxtekbweet\r\n" + //
                        "qtaveuqpifprdoiy\r\n" + //
                        "kpubqyepxqleucem\r\n" + //
                        "wlqrgqmnupwiuory\r\n" + //
                        "rwyocktuqkuhdwxz\r\n" + //
                        "abzjfsdevoygctqv\r\n" + //
                        "zsofhaqqghncmzuw\r\n" + //
                        "lqbjwjqxqbfgdckc\r\n" + //
                        "bkhyxjkrqbbunido\r\n" + //
                        "yepxfjnnhldidsjb\r\n" + //
                        "builayfduxbppafc\r\n" + //
                        "wedllowzeuswkuez\r\n" + //
                        "gverfowxwtnvgrmo\r\n" + //
                        "tpxycfumxdqgntwf\r\n" + //
                        "lqzokaoglwnfcolw\r\n" + //
                        "yqsksyheyspmcdqt\r\n" + //
                        "vufvchcjjcltwddl\r\n" + //
                        "saeatqmuvnoacddt\r\n" + //
                        "dxjngeydvsjbobjs\r\n" + //
                        "ucrcxoakevhsgcep\r\n" + //
                        "cajgwjsfxkasbayt\r\n" + //
                        "hknzmteafsfemwuv\r\n" + //
                        "xxwhxwiinchqqudr\r\n" + //
                        "usfenmavvuevevgr\r\n" + //
                        "kxcobcwhsgyizjok\r\n" + //
                        "vhqnydeboeunnvyk\r\n" + //
                        "bgxbwbxypnxvaacw\r\n" + //
                        "bwjzdypacwgervgk\r\n" + //
                        "rrioqjluawwwnjcr\r\n" + //
                        "fiaeyggmgijnasot\r\n" + //
                        "xizotjsoqmkvhbzm\r\n" + //
                        "uzphtrpxwfnaiidz\r\n" + //
                        "kihppzgvgyoncptg\r\n" + //
                        "hfbkfrxwejdeuwbz\r\n" + //
                        "zgqthtuaqyrxicdy\r\n" + //
                        "zitqdjnnwhznftze\r\n" + //
                        "jnzlplsrwovxlqsn\r\n" + //
                        "bmwrobuhwnwivpca\r\n" + //
                        "uuwsvcdnoyovxuhn\r\n" + //
                        "nmfvoqgoppoyosaj\r\n" + //
                        "hxjkcppaisezygpe\r\n" + //
                        "icvnysgixapvtoos\r\n" + //
                        "vbvzajjgrmjygkhu\r\n" + //
                        "jinptbqkyqredaos\r\n" + //
                        "dpmknzhkhleawfvz\r\n" + //
                        "ouwwkfhcedsgqqxe\r\n" + //
                        "owroouiyptrijzgv\r\n" + //
                        "bewnckpmnbrmhfyu\r\n" + //
                        "evdqxevdacsbfbjb\r\n" + //
                        "catppmrovqavxstn\r\n" + //
                        "dqsbjibugjkhgazg\r\n" + //
                        "mkcldhjochtnvvne\r\n" + //
                        "sblkmhtifwtfnmsx\r\n" + //
                        "lynnaujghehmpfpt\r\n" + //
                        "vrseaozoheawffoq\r\n" + //
                        "ytysdzbpbazorqes\r\n" + //
                        "sezawbudymfvziff\r\n" + //
                        "vrlfhledogbgxbau\r\n" + //
                        "bipdlplesdezbldn\r\n" + //
                        "ermaenjunjtbekeo\r\n" + //
                        "eyaedubkthdecxjq\r\n" + //
                        "gbzurepoojlwucuy\r\n" + //
                        "rsiaqiiipjlouecx\r\n" + //
                        "beqjhvroixhiemtw\r\n" + //
                        "buzlowghhqbcbdwv\r\n" + //
                        "ldexambveeosaimo\r\n" + //
                        "fpyjzachgrhxcvnx\r\n" + //
                        "komgvqejojpnykol\r\n" + //
                        "fxebehjoxdujwmfu\r\n" + //
                        "jnfgvheocgtvmvkx\r\n" + //
                        "qmcclxxgnclkuspx\r\n" + //
                        "rsbelzrfdblatmzu\r\n" + //
                        "vexzwqjqrsenlrhm\r\n" + //
                        "tnfbkclwetommqmh\r\n" + //
                        "lzoskleonvmprdri\r\n" + //
                        "nnahplxqscvtgfwi\r\n" + //
                        "ubqdsflhnmiayzrp\r\n" + //
                        "xtiyqxhfyqonqzrn\r\n" + //
                        "omdtmjeqhmlfojfr\r\n" + //
                        "cnimgkdbxkkcnmkb\r\n" + //
                        "tapyijgmxzbmqnks\r\n" + //
                        "byacsxavjboovukk\r\n" + //
                        "awugnhcrygaoppjq\r\n" + //
                        "yxcnwrvhojpuxehg\r\n" + //
                        "btjdudofhxmgqbao\r\n" + //
                        "nzqlfygiysfuilou\r\n" + //
                        "nubwfjdxavunrliq\r\n" + //
                        "vqxmmhsbmhlewceh\r\n" + //
                        "ygavmcybepzfevrp\r\n" + //
                        "kgflmrqsvxprkqgq\r\n" + //
                        "iaqyqmcaedscmakk\r\n" + //
                        "cvbojnbfmrawxzkh\r\n" + //
                        "jjjrprbnlijzatuw\r\n" + //
                        "lcsudrrfnnggbrmk\r\n" + //
                        "qzgxbiavunawfibc\r\n" + //
                        "gnnalgfvefdfdwwg\r\n" + //
                        "nokmiitzrigxavsc\r\n" + //
                        "etzoxwzxqkkhvais\r\n" + //
                        "urxxfacgjccieufi\r\n" + //
                        "lqrioqhuvgcotuec\r\n" + //
                        "dydbaeyoypsbftra\r\n" + //
                        "hhrotenctylggzaf\r\n" + //
                        "evctqvzjnozpdxzu\r\n" + //
                        "tbpvithmorujxlcp\r\n" + //
                        "pllbtcbrtkfpvxcw\r\n" + //
                        "fzyxdqilyvqreowv\r\n" + //
                        "xdleeddxwvqjfmmt\r\n" + //
                        "fcldzthqqpbswoin\r\n" + //
                        "sgomzrpjfmvgwlzi\r\n" + //
                        "axjyskmtdjbxpwoz\r\n" + //
                        "hcvaevqxsmabvswh\r\n" + //
                        "lfdlsfcwkwicizfk\r\n" + //
                        "isjbwpzdognhoxvm\r\n" + //
                        "oqnexibqxlyxpluh\r\n" + //
                        "zqfbgodsfzwgcwuf\r\n" + //
                        "kvmnwruwsjllbldz\r\n" + //
                        "kghazimdyiyhmokj\r\n" + //
                        "uiktgpsxpoahofxn\r\n" + //
                        "zkdwawxargcmidct\r\n" + //
                        "ftbixlyiprshrjup\r\n" + //
                        "nofhmbxififwroeg\r\n" + //
                        "mcdaqrhplffxrcdt\r\n" + //
                        "fbjxnwojcvlawmlb\r\n" + //
                        "rizoftvwfdhiwyac\r\n" + //
                        "eduogrtyhxfwyars\r\n" + //
                        "zoikunqxgjwfqqwr\r\n" + //
                        "zxwbbpmvctzezaqh\r\n" + //
                        "nghujwyeabwdqnop\r\n" + //
                        "vcxamijpoyyksogn\r\n" + //
                        "jnckdbuteoqlsdae\r\n" + //
                        "jurfqqawafmsiqwv\r\n" + //
                        "inepmztrzehfafie\r\n" + //
                        "tznzkyvzodbrtscf\r\n" + //
                        "xewbavjeppflwscl\r\n" + //
                        "ucndzsorexjlnplo\r\n" + //
                        "jpxbctscngxgusvu\r\n" + //
                        "mfmygcllauzuoaok\r\n" + //
                        "oibkuxhjmhxhhzby\r\n" + //
                        "zjkslwagmeoisunw\r\n" + //
                        "avnnxmopdgvmukuu\r\n" + //
                        "jmaargejcwboqhkt\r\n" + //
                        "yacmpeosarsrfkrv\r\n" + //
                        "iqhgupookcaovwgh\r\n" + //
                        "ebjkdnxwtikqzufc\r\n" + //
                        "imdhbarytcscbsvb\r\n" + //
                        "ifyibukeffkbqvcr\r\n" + //
                        "aloighmyvwybtxhx\r\n" + //
                        "yszqwrutbkiwkxjg\r\n" + //
                        "xyholyzlltjhsuhp\r\n" + //
                        "gykhmrwucneoxcrf\r\n" + //
                        "badkdgqrpjzbabet\r\n" + //
                        "sunaucaucykwtkjj\r\n" + //
                        "pumqkglgfdhneero\r\n" + //
                        "usgtyuestahlydxq\r\n" + //
                        "xmfhflphzeudjsjm\r\n" + //
                        "knywgmclisgpootg\r\n" + //
                        "mtojnyrnvxtweuzb\r\n" + //
                        "uuxufbwfegysabww\r\n" + //
                        "vobhwwocqttlbsik\r\n" + //
                        "yuydfezeqgqxqmnd\r\n" + //
                        "wbqgqkwbibiilhzc\r\n" + //
                        "sfdmgxsbuzsawush\r\n" + //
                        "ilhbxcfgordyxwvp\r\n" + //
                        "ahqoavuysblnqaeg\r\n" + //
                        "plwgtvpgotskmsey\r\n" + //
                        "ewjcmzkcnautrrmp\r\n" + //
                        "tyekgzbznlikcyqj\r\n" + //
                        "bqzctiuaxpriuiga\r\n" + //
                        "bimvbfjkiupyqiys\r\n" + //
                        "mpqtbcxfhwymxncw\r\n" + //
                        "htemlptvqhharjgb\r\n" + //
                        "mqbsmsruwzzxgcxc\r\n" + //
                        "zjyedjwhnvteuaid\r\n" + //
                        "pzoelkoidwglpttc\r\n" + //
                        "efydnsvlfimvwxhx\r\n" + //
                        "gfyhgoeiyjcgfyze\r\n" + //
                        "deqtomhwopmzvjlt\r\n" + //
                        "casafubtkoopuaju\r\n" + //
                        "yylsfarntbucfulg\r\n" + //
                        "mgjwsormkjsrrxan\r\n" + //
                        "lkkenpupgmjpnqqd\r\n" + //
                        "tegweszyohsoluot\r\n" + //
                        "lihsfdwxmxvwdxna\r\n" + //
                        "rrefrjjxerphejwb\r\n" + //
                        "guuazonjoebhymtm\r\n" + //
                        "ysofqzmfmyneziki\r\n" + //
                        "lmjgaliatcpduoal\r\n" + //
                        "qzthcpjwtgahbebr\r\n" + //
                        "wvakvephyukmpemm\r\n" + //
                        "simxacxxzfoaeddw\r\n" + //
                        "aetgqmiqzxbvbviz\r\n" + //
                        "jxlmhdmqggevrxes\r\n" + //
                        "mmuglnjmuddzgaik\r\n" + //
                        "svopsqhtrslgycgc\r\n" + //
                        "xnvcsiiqrcjkvecn\r\n" + //
                        "kkvumxtvashxcops\r\n" + //
                        "bduflsdyeectvcgl\r\n" + //
                        "vfrxbwmmytjvqnsj\r\n" + //
                        "eeqtdneiyiaiofxw\r\n" + //
                        "crtbgknfacjtwkfl\r\n" + //
                        "uuutuoxdsxolpbhd\r\n" + //
                        "lcrztwzreaswovtn\r\n" + //
                        "htorkvnvujmjdqzj\r\n" + //
                        "wttzuzvrzlyhfzyf\r\n" + //
                        "oraewznfwgdsnhuk\r\n" + //
                        "rctlkqqvkwbgrcgk\r\n" + //
                        "cfehrsrqhzyiwtmz\r\n" + //
                        "kbvxwcumjkhvjpui\r\n" + //
                        "xxlocexbmniiakfo\r\n" + //
                        "gtknkkzvykmlqghl\r\n" + //
                        "kcjuxvkuimhwqrtk\r\n" + //
                        "vohekwkuyuoacuww\r\n" + //
                        "vorctgughscysyfo\r\n" + //
                        "zmjevqplngzswxyq\r\n" + //
                        "qhswdrhrijnatkyo\r\n" + //
                        "joakcwpfggtitizs\r\n" + //
                        "juzlwjijcmtswdtq\r\n" + //
                        "icbyaqohpkemhkip\r\n" + //
                        "rpdxgpzxncedmvzh\r\n" + //
                        "rozkmimbqhbhcddv\r\n" + //
                        "wkkypomlvyglpfpf\r\n" + //
                        "jcaqyaqvsefwtaya\r\n" + //
                        "ghvmtecoxlebdwnf\r\n" + //
                        "lqrcyiykkkpkxvqt\r\n" + //
                        "eqlarfazchmzotev\r\n" + //
                        "vqwndafvmpguggef\r\n" + //
                        "dbfxzrdkkrusmdke\r\n" + //
                        "cmjpjjgndozcmefj\r\n" + //
                        "hbrdcwjuyxapyhlo\r\n" + //
                        "mmforetykbosdwce\r\n" + //
                        "zynfntqwblbnfqik\r\n" + //
                        "sodwujfwlasznaiz\r\n" + //
                        "yyvrivjiqnxzqkfp\r\n" + //
                        "uldbskmmjbqllpnm\r\n" + //
                        "fyhhrmrsukeptynl\r\n" + //
                        "hpfjekktvdkgdkzl\r\n" + //
                        "bozhkoekcxzeorob\r\n" + //
                        "uvpptyfrzkvmtoky\r\n" + //
                        "hkhfprmjdpjvfkcb\r\n" + //
                        "igxzwktwsqhsivqu\r\n" + //
                        "qceomwysgkcylipb\r\n" + //
                        "cglateoynluyeqgc\r\n" + //
                        "xcsdfkpeguxgvpfh\r\n" + //
                        "owjhxlcncdgkqyia\r\n" + //
                        "rpbmrpcesiakqpna\r\n" + //
                        "lueszxiourxsmezb\r\n" + //
                        "zelvsowimzkxliwc\r\n" + //
                        "vzxbttoobtvdtkca\r\n" + //
                        "pfxvzphzwscqkzsi\r\n" + //
                        "edsjorainowytbzu\r\n" + //
                        "ipsegdaluoiphmnz\r\n" + //
                        "mkhueokfpemywvuw\r\n" + //
                        "urxdnumhylpafdlc\r\n" + //
                        "ggluurzavsxkvwkl\r\n" + //
                        "ctclphidqgteakox\r\n" + //
                        "tfobosynxsktajuk\r\n" + //
                        "jzrmemhxqmzhllif\r\n" + //
                        "eemwekimdfvqslsx\r\n" + //
                        "yjkwpzrbanoaajgq\r\n" + //
                        "rlxghzanuyeimfhx\r\n" + //
                        "hozbgdoorhthlqpv\r\n" + //
                        "obkbmflhyanxilnx\r\n" + //
                        "xojrippyxjmpzmsz\r\n" + //
                        "ukykmbfheixuviue\r\n" + //
                        "qivlmdexwucqkres\r\n" + //
                        "rmyxxipqkarpjmox\r\n" + //
                        "fgaftctbvcvnrror\r\n" + //
                        "raawxozucfqvasru\r\n" + //
                        "dinpjbdfjfizexdh\r\n" + //
                        "gybxubwnnbuyvjcr\r\n" + //
                        "qrqitdvyoneqyxcg\r\n" + //
                        "jqzcfggayzyoqteo\r\n" + //
                        "cikqpvxizpdbmppm\r\n" + //
                        "stfpldgyhfmucjjv\r\n" + //
                        "slzbcuihmimpduri\r\n" + //
                        "aufajwfrsorqqsnl\r\n" + //
                        "iylmzraibygmgmqj\r\n" + //
                        "lcdyfpcqlktudfmu\r\n" + //
                        "pmomzzsdpvgkkliw\r\n" + //
                        "zpplirgtscfhbrkj\r\n" + //
                        "mvhyerxfiljlotjl\r\n" + //
                        "ofkvrorwwhusyxjx\r\n" + //
                        "xngzmvcgkqfltjpe\r\n" + //
                        "yxfxaqipmysahqqq\r\n" + //
                        "sdqafdzgfdjuabup\r\n" + //
                        "qcqajmerahcdgxfv\r\n" + //
                        "xqimrqtupbapawro\r\n" + //
                        "qfvkqwidzzrehsbl\r\n" + //
                        "himixxvueksiqfdf\r\n" + //
                        "vgtfqpuzxxmhrvvd\r\n" + //
                        "adiioqeiejguaost\r\n" + //
                        "jnzxuycjxvxehbvm\r\n" + //
                        "xedbpxdhphamoodk\r\n" + //
                        "jsrioscmwlsfuxrg\r\n" + //
                        "mtsynnfxunuohbnf\r\n" + //
                        "enamqzfzjunnnkpe\r\n" + //
                        "uwcvfecunobyhces\r\n" + //
                        "ciygixtgbsccpftq\r\n" + //
                        "ewjgcronizkcsfjy\r\n" + //
                        "wztjkoipxsikoimv\r\n" + //
                        "jrgalyvfelwxforw\r\n" + //
                        "imylyalawbqwkrwb\r\n" + //
                        "yflwqfnuuvgjsgcj\r\n" + //
                        "wkysyzusldlojoue\r\n" + //
                        "zopllxnidcffcuau\r\n" + //
                        "bscgwxuprxaerskj\r\n" + //
                        "zvnvprxxjkhnkkpq\r\n" + //
                        "nejwxbhjxxdbenid\r\n" + //
                        "chryiccsebdbcnkc\r\n" + //
                        "guoeefaeafhlgvxh\r\n" + //
                        "nzapxrfrrqhsingx\r\n" + //
                        "mkzvquzvqvwsejqs\r\n" + //
                        "kozmlmbchydtxeeo\r\n" + //
                        "keylygnoqhmfzrfp\r\n" + //
                        "srwzoxccndoxylxe\r\n" + //
                        "uqjzalppoorosxxo\r\n" + //
                        "potmkinyuqxsfdfw\r\n" + //
                        "qkkwrhpbhypxhiun\r\n" + //
                        "wgfvnogarjmdbxyh\r\n" + //
                        "gkidtvepcvxopzuf\r\n" + //
                        "atwhvmmdvmewhzty\r\n" + //
                        "pybxizvuiwwngqej\r\n" + //
                        "zfumwnazxwwxtiry\r\n" + //
                        "keboraqttctosemx\r\n" + //
                        "vtlzxaqdetbhclib\r\n" + //
                        "wjiecykptzexuayl\r\n" + //
                        "ejatfnyjjdawepyk\r\n" + //
                        "mpcrobansyssvmju\r\n" + //
                        "gqukndzganeueabm\r\n" + //
                        "ukzscvomorucdnqd\r\n" + //
                        "wfydhtbzehgwfazx\r\n" + //
                        "mtwqdzlephqvxqmx\r\n" + //
                        "dltmlfxbjopefibh\r\n" + //
                        "atcfrowdflluqtbi\r\n" + //
                        "vowawlophlxaqonw\r\n" + //
                        "vblgdjzvwnocdipw\r\n" + //
                        "uzerzksmkvnlvlhm\r\n" + //
                        "ytjwhpaylohorvxd\r\n" + //
                        "siprvfxvnxcdgofz\r\n" + //
                        "cbhjupewcyjhvtgs\r\n" + //
                        "apqtozaofusmfqli\r\n" + //
                        "tmssrtlxfouowqnr\r\n" + //
                        "ntutrvwnzzgmokes\r\n" + //
                        "zrsgpwdzokztdpis\r\n" + //
                        "nrobvmsxtfmrqdhv\r\n" + //
                        "kadkaftffaziqdze\r\n" + //
                        "yrovbgcyqtlsnoux\r\n" + //
                        "modheiwuhntdecqs\r\n" + //
                        "gzhjypwddizemnys\r\n" + //
                        "gaputpwpcsvzxjho\r\n" + //
                        "bgmouxwoajgaozau\r\n" + //
                        "oxuapfrjcpyakiwt\r\n" + //
                        "kntwbvhuaahdixzj\r\n" + //
                        "epqjdjbnkxdnaccx\r\n" + //
                        "dspltdvznhypykri\r\n" + //
                        "tdrgqmbnagrxdwtt\r\n" + //
                        "njfqawzjggmemtbg\r\n" + //
                        "chpemsgwpzjpdnkk\r\n" + //
                        "fpsrobmbqbmigmwk\r\n" + //
                        "flxptsrqaazmprnl\r\n" + //
                        "nzdunrxlcbfklshm\r\n" + //
                        "miuwljvtkgzdlbnn\r\n" + //
                        "xbhjakklmbhsdmdt\r\n" + //
                        "xwxhsbnrwnegwcov\r\n" + //
                        "pwosflhodjaiexwq\r\n" + //
                        "fhgepuluczttfvqh\r\n" + //
                        "tldxcacbvxyamvkt\r\n" + //
                        "gffxatrjglkcehim\r\n" + //
                        "tzotkdrpxkucsdps\r\n" + //
                        "wxheftdepysvmzbe\r\n" + //
                        "qfooyczdzoewrmku\r\n" + //
                        "rvlwikuqdbpjuvoo\r\n" + //
                        "bcbrnbtfrdgijtzt\r\n" + //
                        "vaxqmvuogsxonlgq\r\n" + //
                        "ibsolflngegravgo\r\n" + //
                        "txntccjmqakcoorp\r\n" + //
                        "vrrbmqaxfbarmlmc\r\n" + //
                        "dzspqmttgsuhczto\r\n" + //
                        "pikcscjunxlwqtiw\r\n" + //
                        "lwzyogwxqitqfqlv\r\n" + //
                        "gsgjsuaqejtzglym\r\n" + //
                        "feyeqguxbgmcmgpp\r\n" + //
                        "gmttebyebdwvprkn\r\n" + //
                        "mzuuwbhzdjfdryxu\r\n" + //
                        "fganrbnplymqbzjx\r\n" + //
                        "cvsrbdcvhtxxdmro\r\n" + //
                        "scmgkjlkqukoamyp\r\n" + //
                        "fkgrqbyqpqcworqc\r\n" + //
                        "hjsrvkdibdjarxxb\r\n" + //
                        "sztzziuqroeidcus\r\n" + //
                        "pxdfvcpvwaddrzwv\r\n" + //
                        "phdqqxleqdjfgfbg\r\n" + //
                        "cqfikbgxvjmnfncy";
        String[] strings = string.split("\r\n", 0);
        for(int i = 0; i < strings.length; i++){
        if (hasDoubles(strings[i]) && hasVowels(strings[i]) && !badCouple(strings[i])){
            System.out.println("Nice String");
            x++;
        }else{
            System.out.println("Naughty String");
        }}
        System.out.println(x);
    }
}
